# Generated by Django 4.1.2 on 2022-10-10 17:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("username", models.CharField(max_length=255, unique=True)),
                ("password", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=255, unique=True)),
                ("address", models.CharField(blank=True, max_length=255, null=True)),
                ("full_name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "Quản trị viên"),
                            ("staff", "Nhân viên kinh doanh"),
                            ("customer", "Khách hàng"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("male", "Nam"), ("female", "Nữ")],
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("is_superuser", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("is_anonymous", models.BooleanField(default=False)),
                ("date_joined", models.DateField(auto_now_add=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("price", models.FloatField(blank=True, null=True)),
                ("number_of_surveys", models.IntegerField(blank=True, null=True)),
                (
                    "number_of_surveys_question",
                    models.IntegerField(blank=True, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CustomerHandlerRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "customer_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "method",
                    models.CharField(
                        blank=True,
                        choices=[("post", "Thêm"), ("put", "Sửa"), ("delete", "Xóa")],
                        max_length=255,
                        null=True,
                    ),
                ),
                ("data", models.JSONField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Đang chờ"),
                            ("approved", "Đã duyệt"),
                            ("rejected", "Đã từ chối"),
                        ],
                        default="pending",
                        max_length=255,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
